### ISSUE TITLE
halo persists after taking off the antimayor suit

### ISSUE THREAD

**Issue by duckmammal** [scrudgey/yogurt#185] opened 2020-04-09 17:37 UTC
![image](https://user-images.githubusercontent.com/4755233/78924071-0f3e4b80-7a4e-11ea-940d-d9e9a9148959.png)

**Comment by ryan-foltz-exa** [comment] 2020-04-09 17:44
duplicate of #115

**Closed** 2020-04-11 22:05 UTC
Labels: duplicate
