### ISSUE TITLE
you can hypnotize ghosts, but their movements are not controlled by the player

### ISSUE THREAD

**Issue by tim-win** [scrudgey/yogurt#118] opened 2020-04-05 05:49 UTC
the player starts to wander off which could leave you stuck. Although I didn't try exploding my head as a ghost, which seems like a missed opportunity.

**Comment by scrudgey** [comment] 2020-04-05 19:18
believe it or not, but related to the same general issue as #88

**Comment by scrudgey** [comment] 2020-04-14 18:43
going to close this as a duplicate of #88

**Closed by scrudgey** 2020-04-14 18:43 UTC
Labels: bug, duplicate
