### ISSUE TITLE
Flushing items down the toliet doesn't refresh the sewers. 

### ISSUE THREAD

**Issue by WarlockD** [scrudgey/yogurt#254] opened 2021-06-13 01:51 UTC
I think its related to the other bug about the crash in the sewers.  You got to explode head and restart the day.  Saving and reloading doesn't seem to do it.

**Comment by scrudgey** [comment] 2021-06-19 17:06
100% related, closing this as duplicate of https://github.com/scrudgey/yogurt/issues/253

**Closed as completed by scrudgey** 2021-06-19 17:06 UTC
Labels: duplicate
