### ISSUE TITLE
Didn't receive items on some days after checking email.

### ISSUE THREAD

**Issue by dddanger** [scrudgey/yogurt#94] opened 2020-04-04 22:50 UTC
1) Some of the later post-yogurt-commercial emails say that a package is going to be delivered, but there's nothing there. It happened ~2x.

2) Anti-mayor commercial reward never arrived, or didn't arrive at the right time. The hat of clear-headedness eventually showed up several days later randomly if this was the reward, or maybe this a separate bug.

**Comment by scrudgey** [comment] 2020-04-04 23:23
currently, no there are no rewards for moon commercial / gravy commecial, vampire commercial yields hat of clearheadedness

**Comment by scrudgey** [comment] 2020-04-04 23:27
gonna close this for now, i think it's behaving as intended

**Closed by scrudgey** 2020-04-04 23:27 UTC
