### ISSUE TITLE
Mouse-over the bottom and right side of the screen shows "NeoUICanvas" message

### ISSUE THREAD

**Issue by dddanger** [scrudgey/yogurt#111] opened 2020-04-04 23:09 UTC
Most screens have this bug. Mousing over the bottom and right side of the screen shows "NeoUICanvas" message which shouldn't exist.

**Comment by scrudgey** [comment] 2020-04-04 23:29
duplicate of #54

**Closed by scrudgey** 2020-04-04 23:29 UTC
Labels: duplicate
